[package]
name = "wide"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-simd="0.5.0"
simd-abstraction="0.5.0"

[dev-dependencies]
criterion = "0.3"
rand = "0.8.5"
rand_pcg = "0.3.1"
quickcheck = "1.0"
quickcheck_macros = "1.0"

[[bench]]
name = "core_ext"
harness = false
